# Generated by Django 5.2.12 on 2026-09-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gown',
            name='color_histogram',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gown',
            name='fashion_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
